### PR TITLE
some cleaning

### PR DESCRIPTION
**Pull request by eleminer**
some cleaning, removing the empty readme and some obsolete characters in display lib

### CODE REVIEW

**Comment by noah1400** [comment]
@eleminer fix Sonarcloud remarks

**Comment by eleminer** [comment]
> @eleminer fix Sonarcloud remarks

ok, in progress

**Comment by eleminer** [comment]
should work now, please merge

**Review by noah1400 — APPROVED** [review]
Looks good. Ready to merge

**Pull request merged**
