### PR TITLE
120 timer start stop

### PR DESCRIPTION
**Pull request by glikaa**
stopwatch with start and end date/time, timer libary used,  check to with project time gets assiged when connection to database is ready to fix the time logs

### CODE REVIEW

**Comment by eleminer** [comment]
one moment, i want to check with the pos absolute.

**Comment by eleminer** [comment]
ok, its good

**Review by eleminer — APPROVED** [review]

**Comment by noah1400** [comment]
Could you rename `TimeLog` to `TimeEntry`, so we can keep the naming in all modules and in the Server application the Same.

**Comment by glikaa** [comment]
of course

**Pull request merged**
